import os
import sys
import xml.etree.ElementTree as ET
import json
import shutil
import re
import subprocess
import urllib.request
import html

def clean_html(html_content):
    # Strip HTML tags and normalize whitespace
    text = re.sub('<[^>]*>', ' ', html_content)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def organize_course(extract_dir, output_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Load structure generated by extract_edx.py
    struct_path = "course_structure.json"
    if not os.path.exists(struct_path):
        print(f"Error: {struct_path} not found. Run extract_edx.py first.")
        sys.exit(1)

    with open(struct_path, "r", encoding="utf-8") as f:
        structure = json.load(f)

    manifest = []

    for i, chapter in enumerate(structure["chapters"]):
        # Create a clean folder name for the chapter (match old scheme: 01_Welcome___What_..., not 01_1__Welcome_...)
        title_for_slug = re.sub(r'^\s*\d+\.?\s*', '', chapter['title'].strip())  # strip leading "1. " etc.
        clean_title = re.sub(r'[^a-zA-Z0-9]', '_', title_for_slug)
        clean_title = re.sub(r'_+', '_', clean_title).strip('_')  # collapse and trim underscores
        ch_name = f"{i+1:02d}_{clean_title}"
        ch_dir = os.path.join(output_dir, ch_name)
        os.makedirs(ch_dir, exist_ok=True)
        
        chapter_manifest = {"chapter": chapter['title'], "files": []}
        merged_text = []

        for seq in chapter["sequentials"]:
            for vert in seq["verticals"]:
                for comp in vert["components"]:
                    # 1. Process HTML Content
                    if comp["type"] == "html":
                        html_path = os.path.join(extract_dir, "course", "html", f"{comp['url_name']}.html")
                        if os.path.exists(html_path):
                            try:
                                with open(html_path, "r", encoding="utf-8") as hf:
                                    merged_text.append(clean_html(hf.read()))
                            except Exception as e:
                                print(f"Error reading HTML {comp['url_name']}: {e}")
                    
                    # 2. Process Video Content (Download & Convert)
                    elif comp["type"] == "video":
                        video_xml_path = os.path.join(extract_dir, "course", "video", f"{comp['url_name']}.xml")
                        if os.path.exists(video_xml_path):
                            try:
                                tree = ET.parse(video_xml_path)
                                root = tree.getroot()
                                
                                # Prefer vertical title (what edX shows as section), then video display_name, then client_video_id
                                video_title = html.unescape(root.get("display_name", comp["url_name"]))
                                vert_title = html.unescape((vert.get("title") or "").strip())
                                if vert_title and len(vert_title) > len(video_title):
                                    video_title = vert_title
                                video_asset = root.find(".//video_asset")
                                if video_asset is not None and video_asset.get("client_video_id"):
                                    client_id = video_asset.get("client_video_id", "").strip()
                                    if client_id:
                                        orig_name = re.sub(r"\.[^.]+$", "", client_id)  # strip extension
                                        generic = video_title.strip().lower() in ("video", "recording", "teaser") or (
                                            len(video_title.split()) <= 3 and "recording" in video_title.lower()
                                        )
                                        if generic or len(orig_name) > len(video_title):
                                            video_title = orig_name
                                clean_vid_name = re.sub(r"[^a-zA-Z0-9]", "_", video_title)
                                clean_vid_name = re.sub(r"_+", "_", clean_vid_name).strip("_")
                                
                                # Find direct MP4 link in edX metadata
                                for asset in root.findall(".//video_asset/encoded_video"):
                                    vid_url = asset.get('url')
                                    if vid_url and vid_url.endswith('.mp4'):
                                        mp3_filename = f"{clean_vid_name}.mp3"
                                        mp3_path = os.path.join(ch_dir, mp3_filename)
                                        temp_mp4 = os.path.join(ch_dir, "temp_download.mp4")
                                        
                                        print(f"Downloading edX MP4: '{video_title}'...")
                                        # Use User-Agent to bypass 403 Forbidden errors from CDN
                                        req = urllib.request.Request(vid_url, headers={'User-Agent': 'Mozilla/5.0'})
                                        with urllib.request.urlopen(req) as response, open(temp_mp4, 'wb') as out_file:
                                            shutil.copyfileobj(response, out_file)
                                        
                                        print(f"Converting to MP3: {mp3_filename}...")
                                        subprocess.run(["ffmpeg", "-y", "-i", temp_mp4, "-q:a", "0", "-map", "a", mp3_path], 
                                                     capture_output=True, check=True)
                                        os.remove(temp_mp4)
                                        
                                        chapter_manifest["files"].append({
                                            "name": mp3_filename,
                                            "path": mp3_path,
                                            "type": "audio"
                                        })
                                        break
                            except Exception as e:
                                print(f"Error processing video {comp['url_name']}: {e}")

        # Save merged text content for NoteBookLM
        if merged_text:
            merged_filename = f"{ch_name}.txt"
            merged_path = os.path.join(ch_dir, merged_filename)
            with open(merged_path, "w", encoding="utf-8") as mf:
                mf.write("\n\n---\n\n".join(merged_text))
            chapter_manifest["files"].append({"name": merged_filename, "path": merged_path, "type": "text"})

        manifest.append(chapter_manifest)

    # Process Global Assets (Existing documents/audio)
    static_output = os.path.join(output_dir, "Global_Assets")
    static_src = os.path.join(extract_dir, "course", "static")
    if os.path.exists(static_src):
        os.makedirs(static_output, exist_ok=True)
        for f in os.listdir(static_src):
            src_f = os.path.join(static_src, f)
            if os.path.isfile(src_f):
                ext = os.path.splitext(f)[1].lower()
                if ext in [".pdf", ".docx", ".xlsx", ".txt"]:
                    shutil.copy2(src_f, os.path.join(static_output, f))

    with open("processing_manifest.json", "w", encoding="utf-8") as f:
        # Save relative paths for subagent compatibility
        json.dump(manifest, f, indent=4)
    print("[OK] Organization and media processing complete.")

if __name__ == "__main__":
    organize_course("edx_export", "Organized_Course_Content")